/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class C_ArchivoB extends javax.swing.JFrame
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(C_ArchivoB.class.getName());

    /**
     * Creates new form C_ArchivoB
     */
    public C_ArchivoB()
    {
        initComponents();
    }

    private void seleccionarArchivo(JTextField txtDestino, JLabel lblpreview)
    {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos binarios (*.bin , *.dat)", "bin", "dat");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);

        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                File archivo = chooser.getSelectedFile();

                String ruta = archivo.getAbsolutePath();
                txtDestino.setText(ruta);

                byte[] datos = java.nio.file.Files.readAllBytes(archivo.toPath());

                lblpreview.setText("Archivo Cargado : " + datos.length + "bytes");

                lblpreview.setIcon(null);
                System.out.println("Archivo cargado correctamente ");

                new MenuPrincipal().setVisible(true);
                dispose();

            } catch (Exception e)
            {
                e.printStackTrace();
                lblpreview.setText("ERROR ... \n no se cargo correctamente ");
            }
        }
        //new MenuPrincipal().setVisible(true);
        //dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BtnCargarAr = new javax.swing.JButton();
        lblPreview = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cargar Archivo Binario");

        BtnCargarAr.setBackground(new java.awt.Color(0, 204, 0));
        BtnCargarAr.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        BtnCargarAr.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargarAr.setText("Cargar archivo");
        BtnCargarAr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCargarAr.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    seleccionarArchivo(txtDestino, lblPreview);
                }
            });

            lblPreview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
            lblPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblPreview.setText("Sin archivo");

            txtDestino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtDestino.addActionListener(this::txtDestinoActionPerformed);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnCargarAr)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(150, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(lblPreview)
                    .addGap(18, 18, 18)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)
                    .addComponent(BtnCargarAr)
                    .addContainerGap(100, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDestinoActionPerformed
    {//GEN-HEADEREND:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(new FlatMacDarkLaf()); //FlatMacDarkLaf()
        } catch (Exception ex)
        {
            System.out.println("Failed to initialize LaF");
        }
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new C_ArchivoB().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargarAr;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JTextField txtDestino;
    // End of variables declaration//GEN-END:variables
}
