/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.util.Date;
import java.util.Random;
import javax.swing.UIManager;


/**
 *
 * @author DELL
 */
public class MenuPrincipal extends javax.swing.JFrame
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal()
    {
        initComponents();
        //AgrImage();
        MostrarmensajeB(null);
    }
    
    private void MostrarmensajeB(java.awt.event.WindowEvent evt)
    {
        
        String [] mensajeBienvenida =
        {
          "Bienvenido a tu buscador favorito",
          "Encuentra los mejores precios",
          "Mejores servicios",
          "Compara precios y servicios",
          "Los mejores precios"
        };
        Random random = new Random();
        int indice = random.nextInt(mensajeBienvenida.length);
        
        mensajesBien.setText(mensajeBienvenida[indice]);
    }

    private void AgrImage()
    {
        // panel 1
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/GUI/PanelPrincipal.jpg"));

        javax.swing.JLabel fondo = new javax.swing.JLabel();

        L_Serv.setLayout(new java.awt.BorderLayout());

        L_Serv.add(fondo);

        L_Serv.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e)
            {

                java.awt.Image imgEscalada = icon.getImage().getScaledInstance(
                        L_Serv.getWidth(),
                        L_Serv.getHeight(),
                        java.awt.Image.SCALE_SMOOTH
                );

                fondo.setIcon(new javax.swing.ImageIcon(imgEscalada));
                fondo.setBounds(0, 0, L_Serv.getWidth(), L_Serv.getHeight());
            }
        });

        // panel 2
        javax.swing.ImageIcon icon2 = new javax.swing.ImageIcon(getClass().getResource("/GUI/buscarauto.jpg"));

        javax.swing.JLabel fondo2 = new javax.swing.JLabel();

        L_Auto.setLayout(new java.awt.BorderLayout());

        L_Auto.add(fondo2);

        L_Auto.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e)
            {

                java.awt.Image imgEscalada = icon2.getImage().getScaledInstance(
                        L_Auto.getWidth(),
                        L_Auto.getHeight(),
                        java.awt.Image.SCALE_SMOOTH
                );

                fondo2.setIcon(new javax.swing.ImageIcon(imgEscalada));
                fondo2.setBounds(0, 0, L_Auto.getWidth(), L_Auto.getHeight());
            }
        });

        //panel 3
        javax.swing.ImageIcon icon3 = new javax.swing.ImageIcon(getClass().getResource("/GUI/Comparador.jpg"));

        javax.swing.JLabel fondo3 = new javax.swing.JLabel();

        CompServ.setLayout(new java.awt.BorderLayout());

        CompServ.add(fondo3);

        CompServ.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e)
            {

                java.awt.Image imgEscalada = icon3.getImage().getScaledInstance(
                        CompServ.getWidth(),
                        CompServ.getHeight(),
                        java.awt.Image.SCALE_SMOOTH
                );

                fondo3.setIcon(new javax.swing.ImageIcon(imgEscalada));
                fondo3.setBounds(0, 0, CompServ.getWidth(), CompServ.getHeight());
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        L_Serv = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelServicio = new javax.swing.JLabel();
        jComboBoxServicios = new javax.swing.JComboBox<>();
        jLabelMarca = new javax.swing.JLabel();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        BtnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        L_Auto = new javax.swing.JPanel();
        jLabelBucarAut = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CompServ = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Lib_Serv = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButtonElimFech = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mensajesBien = new javax.swing.JLabel();
        jTabbedPaneInicio = new javax.swing.JTabbedPane();
        jPanelInAut = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPlacaA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldModeloA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDCfechaIn = new com.toedter.calendar.JDateChooser();
        jTextFieldAnioA = new javax.swing.JTextField();
        jPanelServicio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldServicioNom = new javax.swing.JTextField();
        jTextFieldServicioPrec = new javax.swing.JTextField();
        jTextFieldServicioCap = new javax.swing.JTextField();
        jButtonMod1 = new javax.swing.JButton();
        jButtonGuardar1 = new javax.swing.JButton();
        jButtonNuevo1 = new javax.swing.JButton();
        jPanelSucursal = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldSucNom = new javax.swing.JTextField();
        jTextFieldSucDir = new javax.swing.JTextField();
        jTextFieldSucRes = new javax.swing.JTextField();
        jButtonMod2 = new javax.swing.JButton();
        jButtonGuardar2 = new javax.swing.JButton();
        jButtonNuevo2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCiudNom = new javax.swing.JTextField();
        jButtonMod3 = new javax.swing.JButton();
        jButtonGuardar3 = new javax.swing.JButton();
        jButtonNuevo3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldMarNom = new javax.swing.JTextField();
        jButtonGuardar4 = new javax.swing.JButton();
        jButtonNuevo4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(39, 59, 98));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("Menú Principal");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jLabelServicio.setText("Servicio");

        jComboBoxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toluca", "CDMX", "Metepec", "San Mateo Atenco" }));
        jComboBoxServicios.addActionListener(this::jComboBoxServiciosActionPerformed);

        jLabelMarca.setText("Marca");

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cupra", "Nissan", "Toyota", "MG", "BYD" , "otras" }));

        BtnBuscar.setBackground(new java.awt.Color(37, 103, 236));
        BtnBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(this::BtnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMarca)
                    .addComponent(jLabelServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscar))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarca)
                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Sucursales que cuentan con el servicio y cupo disponible");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Ciudad", "Sucursal", "Capacidad total", "Cupo disponible", "Responsable"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("Buscar el mejor servicio");

        javax.swing.GroupLayout L_ServLayout = new javax.swing.GroupLayout(L_Serv);
        L_Serv.setLayout(L_ServLayout);
        L_ServLayout.setHorizontalGroup(
            L_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L_ServLayout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(L_ServLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(L_ServLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 287, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        L_ServLayout.setVerticalGroup(
            L_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L_ServLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Localizar tu Servicio", L_Serv);

        jLabelBucarAut.setText("Placa");

        jButton1.setBackground(new java.awt.Color(37, 103, 236));
        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar mi auto");

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("Buscar autos por placa");

        javax.swing.GroupLayout L_AutoLayout = new javax.swing.GroupLayout(L_Auto);
        L_Auto.setLayout(L_AutoLayout);
        L_AutoLayout.setHorizontalGroup(
            L_AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L_AutoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(L_AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(L_AutoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(L_AutoLayout.createSequentialGroup()
                        .addComponent(jLabelBucarAut, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50))))
        );
        L_AutoLayout.setVerticalGroup(
            L_AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L_AutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(L_AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBucarAut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Localizar tu Auto", L_Auto);

        jButton2.setBackground(new java.awt.Color(37, 103, 236));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Comparar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setText("Comparar Servicios");

        jLabel3.setText("Servicio");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Marca", "Ciudad", "Sucursal", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout CompServLayout = new javax.swing.GroupLayout(CompServ);
        CompServ.setLayout(CompServLayout);
        CompServLayout.setHorizontalGroup(
            CompServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompServLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(CompServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompServLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CompServLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(94, 94, 94)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompServLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        CompServLayout.setVerticalGroup(
            CompServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompServLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(CompServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comparar Servicios", CompServ);

        jLabel10.setText("Fecha de ingreso");

        jButtonElimFech.setBackground(new java.awt.Color(255, 0, 0));
        jButtonElimFech.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonElimFech.setForeground(new java.awt.Color(255, 255, 255));
        jButtonElimFech.setText("Eliminar");
        jButtonElimFech.addActionListener(this::jButtonElimFechActionPerformed);

        javax.swing.GroupLayout Lib_ServLayout = new javax.swing.GroupLayout(Lib_Serv);
        Lib_Serv.setLayout(Lib_ServLayout);
        Lib_ServLayout.setHorizontalGroup(
            Lib_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lib_ServLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addGap(104, 104, 104)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonElimFech)
                .addGap(40, 40, 40))
        );
        Lib_ServLayout.setVerticalGroup(
            Lib_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lib_ServLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(Lib_ServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonElimFech)
                    .addComponent(jLabel10)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Liberar tu Auto", Lib_Serv);

        mensajesBien.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        mensajesBien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajesBien.setText("Bienvenido");

        jLabel6.setText("Placa");

        jLabel7.setText("Modelo");

        jLabel8.setText("Año");

        jLabel9.setText("Fecha de ingreso ");

        jButtonNuevo.setBackground(new java.awt.Color(0, 204, 0));
        jButtonNuevo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(this::jButtonNuevoActionPerformed);

        jButtonGuardar.setBackground(new java.awt.Color(37, 103, 236));
        jButtonGuardar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonMod.setBackground(new java.awt.Color(204, 204, 0));
        jButtonMod.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonMod.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod.setText("Modificar");

        jButtonEliminar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonEliminar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");

        jButton7.setText("jButton7");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jTextFieldAnioA.addActionListener(this::jTextFieldAnioAActionPerformed);

        javax.swing.GroupLayout jPanelInAutLayout = new javax.swing.GroupLayout(jPanelInAut);
        jPanelInAut.setLayout(jPanelInAutLayout);
        jPanelInAutLayout.setHorizontalGroup(
            jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInAutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNuevo)
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCfechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnioA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldModeloA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPlacaA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMod)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInAutLayout.setVerticalGroup(
            jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInAutLayout.createSequentialGroup()
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInAutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldPlacaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jTextFieldModeloA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldAnioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInAutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(19, 19, 19)
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCfechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(61, 61, 61)
                .addGroup(jPanelInAutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonMod)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButton7))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPaneInicio.addTab("Autos", jPanelInAut);

        jLabel11.setText("Nombre");

        jLabel12.setText("Precio");

        jLabel13.setText("Capacidad");

        jTextFieldServicioPrec.addActionListener(this::jTextFieldServicioPrecActionPerformed);

        jButtonMod1.setBackground(new java.awt.Color(204, 204, 0));
        jButtonMod1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonMod1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod1.setText("Modificar");

        jButtonGuardar1.setBackground(new java.awt.Color(37, 103, 236));
        jButtonGuardar1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar1.setText("Guardar");
        jButtonGuardar1.addActionListener(this::jButtonGuardar1ActionPerformed);

        jButtonNuevo1.setBackground(new java.awt.Color(0, 204, 0));
        jButtonNuevo1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonNuevo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo1.setText("Nuevo");
        jButtonNuevo1.addActionListener(this::jButtonNuevo1ActionPerformed);

        javax.swing.GroupLayout jPanelServicioLayout = new javax.swing.GroupLayout(jPanelServicio);
        jPanelServicio.setLayout(jPanelServicioLayout);
        jPanelServicioLayout.setHorizontalGroup(
            jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldServicioNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServicioPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServicioCap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
            .addGroup(jPanelServicioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonNuevo1)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar1)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod1)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanelServicioLayout.setVerticalGroup(
            jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldServicioNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldServicioPrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldServicioCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo1)
                    .addComponent(jButtonGuardar1)
                    .addComponent(jButtonMod1))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPaneInicio.addTab("Servicio", jPanelServicio);

        jLabel14.setText("Nombre");

        jLabel15.setText("Dirección");

        jLabel16.setText("Responsable");

        jTextFieldSucDir.addActionListener(this::jTextFieldSucDirActionPerformed);

        jButtonMod2.setBackground(new java.awt.Color(204, 204, 0));
        jButtonMod2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonMod2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod2.setText("Modificar");

        jButtonGuardar2.setBackground(new java.awt.Color(37, 103, 236));
        jButtonGuardar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar2.setText("Guardar");
        jButtonGuardar2.addActionListener(this::jButtonGuardar2ActionPerformed);

        jButtonNuevo2.setBackground(new java.awt.Color(0, 204, 0));
        jButtonNuevo2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonNuevo2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo2.setText("Nuevo");
        jButtonNuevo2.addActionListener(this::jButtonNuevo2ActionPerformed);

        javax.swing.GroupLayout jPanelSucursalLayout = new javax.swing.GroupLayout(jPanelSucursal);
        jPanelSucursal.setLayout(jPanelSucursalLayout);
        jPanelSucursalLayout.setHorizontalGroup(
            jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSucursalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSucursalLayout.createSequentialGroup()
                        .addComponent(jButtonNuevo2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMod2))
                    .addGroup(jPanelSucursalLayout.createSequentialGroup()
                        .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(167, 167, 167)
                        .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSucRes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSucDir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSucNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelSucursalLayout.setVerticalGroup(
            jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSucursalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSucursalLayout.createSequentialGroup()
                        .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldSucNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15))
                    .addComponent(jTextFieldSucDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldSucRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo2)
                    .addComponent(jButtonGuardar2)
                    .addComponent(jButtonMod2))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPaneInicio.addTab("Sucursal", jPanelSucursal);

        jLabel17.setText("Nombre");

        jTextFieldCiudNom.addActionListener(this::jTextFieldCiudNomActionPerformed);

        jButtonMod3.setBackground(new java.awt.Color(204, 204, 0));
        jButtonMod3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonMod3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod3.setText("Modificar");

        jButtonGuardar3.setBackground(new java.awt.Color(37, 103, 236));
        jButtonGuardar3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonGuardar3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar3.setText("Guardar");
        jButtonGuardar3.addActionListener(this::jButtonGuardar3ActionPerformed);

        jButtonNuevo3.setBackground(new java.awt.Color(0, 204, 0));
        jButtonNuevo3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonNuevo3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo3.setText("Nuevo");
        jButtonNuevo3.addActionListener(this::jButtonNuevo3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCiudNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonNuevo3)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar3)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod3)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldCiudNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo3)
                    .addComponent(jButtonGuardar3)
                    .addComponent(jButtonMod3))
                .addGap(79, 79, 79))
        );

        jTabbedPaneInicio.addTab("Ciudad", jPanel1);

        jLabel18.setText("Nombre");

        jButtonGuardar4.setBackground(new java.awt.Color(37, 103, 236));
        jButtonGuardar4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonGuardar4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar4.setText("Guardar");
        jButtonGuardar4.addActionListener(this::jButtonGuardar4ActionPerformed);

        jButtonNuevo4.setBackground(new java.awt.Color(0, 204, 0));
        jButtonNuevo4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButtonNuevo4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo4.setText("Nuevo");
        jButtonNuevo4.addActionListener(this::jButtonNuevo4ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel18)
                .addGap(198, 198, 198)
                .addComponent(jTextFieldMarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonNuevo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar4)
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jTextFieldMarNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo4)
                    .addComponent(jButtonGuardar4))
                .addGap(88, 88, 88))
        );

        jTabbedPaneInicio.addTab("Marca", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensajesBien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneInicio))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(mensajesBien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneInicio)
                .addContainerGap())
        );

        mensajesBien.getAccessibleContext().setAccessibleName("Bienvenido\n");
        mensajesBien.getAccessibleContext().setAccessibleParent(mensajesBien);

        jTabbedPane1.addTab("Inicio", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxServiciosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxServiciosActionPerformed
    {//GEN-HEADEREND:event_jComboBoxServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServiciosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevoActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnBuscarActionPerformed
    {//GEN-HEADEREND:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void jButtonElimFechActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonElimFechActionPerformed
    {//GEN-HEADEREND:event_jButtonElimFechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonElimFechActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGuardarActionPerformed
    {//GEN-HEADEREND:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        Date FechaIngreso = jDCfechaIn.getDate();
        long fecha = FechaIngreso.getTime();
        java.sql.Date fecha_sql = new java.sql.Date(fecha);
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldAnioAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldAnioAActionPerformed
    {//GEN-HEADEREND:event_jTextFieldAnioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioAActionPerformed

    private void jTextFieldServicioPrecActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldServicioPrecActionPerformed
    {//GEN-HEADEREND:event_jTextFieldServicioPrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServicioPrecActionPerformed

    private void jTextFieldSucDirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldSucDirActionPerformed
    {//GEN-HEADEREND:event_jTextFieldSucDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSucDirActionPerformed

    private void jTextFieldCiudNomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldCiudNomActionPerformed
    {//GEN-HEADEREND:event_jTextFieldCiudNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudNomActionPerformed

    private void jButtonGuardar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGuardar1ActionPerformed
    {//GEN-HEADEREND:event_jButtonGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardar1ActionPerformed

    private void jButtonNuevo1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevo1ActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevo1ActionPerformed

    private void jButtonGuardar2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGuardar2ActionPerformed
    {//GEN-HEADEREND:event_jButtonGuardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardar2ActionPerformed

    private void jButtonNuevo2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevo2ActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevo2ActionPerformed

    private void jButtonGuardar3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGuardar3ActionPerformed
    {//GEN-HEADEREND:event_jButtonGuardar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardar3ActionPerformed

    private void jButtonNuevo3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevo3ActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevo3ActionPerformed

    private void jButtonGuardar4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGuardar4ActionPerformed
    {//GEN-HEADEREND:event_jButtonGuardar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardar4ActionPerformed

    private void jButtonNuevo4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevo4ActionPerformed
    {//GEN-HEADEREND:event_jButtonNuevo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevo4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
       
        try
        {
            UIManager.setLookAndFeel(new FlatMacDarkLaf()); //FlatMacDarkLaf()
        } catch (Exception ex)
        {
            System.out.println("Failed to initialize LaF");
        }
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JPanel CompServ;
    private javax.swing.JPanel L_Auto;
    private javax.swing.JPanel L_Serv;
    private javax.swing.JPanel Lib_Serv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonElimFech;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardar1;
    private javax.swing.JButton jButtonGuardar2;
    private javax.swing.JButton jButtonGuardar3;
    private javax.swing.JButton jButtonGuardar4;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMod1;
    private javax.swing.JButton jButtonMod2;
    private javax.swing.JButton jButtonMod3;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonNuevo1;
    private javax.swing.JButton jButtonNuevo2;
    private javax.swing.JButton jButtonNuevo3;
    private javax.swing.JButton jButtonNuevo4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JComboBox<String> jComboBoxServicios;
    private com.toedter.calendar.JDateChooser jDCfechaIn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBucarAut;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelServicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelInAut;
    private javax.swing.JPanel jPanelServicio;
    private javax.swing.JPanel jPanelSucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneInicio;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAnioA;
    private javax.swing.JTextField jTextFieldCiudNom;
    private javax.swing.JTextField jTextFieldMarNom;
    private javax.swing.JTextField jTextFieldModeloA;
    private javax.swing.JTextField jTextFieldPlacaA;
    private javax.swing.JTextField jTextFieldServicioCap;
    private javax.swing.JTextField jTextFieldServicioNom;
    private javax.swing.JTextField jTextFieldServicioPrec;
    private javax.swing.JTextField jTextFieldSucDir;
    private javax.swing.JTextField jTextFieldSucNom;
    private javax.swing.JTextField jTextFieldSucRes;
    private javax.swing.JLabel mensajesBien;
    // End of variables declaration//GEN-END:variables
}
