/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import java.util.ArrayList;

/**
 *
 * @author vllnm
 */
public class VtnEliminarCiudad extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnEliminarCiudad
     */
    public VtnEliminarCiudad(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cmbBoxMarca = new javax.swing.JComboBox<>();
        cmbBoxCiudadAEliminar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnSalirEliminarCiudad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        cmbBoxMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxMarcaActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Marca");

        jLabel2.setText("Seleccionar ciudad a Eliminar");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalirEliminarCiudad.setText("Salir");
        btnSalirEliminarCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirEliminarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxCiudadAEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(64, 64, 64)
                        .addComponent(btnSalirEliminarCiudad)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxCiudadAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalirEliminarCiudad))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed

            
        if (cmbBoxMarca.getSelectedIndex() == -1)
        {
            MenuPrincipal.muestraMensaje("Selecciona una marca primero");
            return; 
        }

        if (cmbBoxCiudadAEliminar.getSelectedIndex() == -1)
        {
            MenuPrincipal.muestraMensaje("Selecciona una ciudad");
            return; 
         }

  
        String nomMarca = (String) cmbBoxMarca.getSelectedItem();
        String nomCiudad = (String) cmbBoxCiudadAEliminar.getSelectedItem();

        String[] c =
        {
            nomMarca, nomCiudad
        };


        datos.getMultilista().elimina(c, 0, datos.getMultilista().getR());

        cmbBoxCiudadAEliminar.removeItem(nomCiudad);

        MenuPrincipal.muestraMensaje("Ciudad eliminada correctamente.");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirEliminarCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirEliminarCiudadActionPerformed
    {//GEN-HEADEREND:event_btnSalirEliminarCiudadActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirEliminarCiudadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cmbBoxMarca.removeAllItems();

        Nodo auxBusqueda = datos.getMultilista().getR();
        ArrayList<String> cadenas = new ArrayList<String>();

        while (auxBusqueda != null)
        {
            cadenas.add(auxBusqueda.getEt());
            auxBusqueda = auxBusqueda.getSig();
        }

        if (cadenas.size() != 0)
        {
            for (int i = 0; i < cadenas.size(); i++)
            {
                cmbBoxMarca.addItem(cadenas.get(i));
            }
        }
        cmbBoxMarca.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void cmbBoxMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxMarcaActionPerformed
    {//GEN-HEADEREND:event_cmbBoxMarcaActionPerformed
        cmbBoxCiudadAEliminar.removeAllItems();

        String nomMarca = (String) cmbBoxMarca.getSelectedItem();

        if (nomMarca != null)
        {
            Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);

            if (nodoMarca != null)
            {
                Nodo busquedaC = nodoMarca.getAbj();

                while (busquedaC != null)
                {

                    cmbBoxCiudadAEliminar.addItem(busquedaC.getEt());

                    busquedaC = busquedaC.getSig();
                }
            }
        }
        cmbBoxCiudadAEliminar.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnEliminarCiudad dialog = new VtnEliminarCiudad(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalirEliminarCiudad;
    private javax.swing.JComboBox<String> cmbBoxCiudadAEliminar;
    private javax.swing.JComboBox<String> cmbBoxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
