/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import java.util.ArrayList;

/**
 *
 * @author vllnm
 */
public class VtnEliminaMarcas extends javax.swing.JDialog
{
    Datos datos;
    /**
     * Creates new form VtnEliminaMarcas
     */
    public VtnEliminaMarcas(java.awt.Frame parent,boolean modal, Datos datosMP)
    {
        super(parent,modal);
        this.datos=datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        textFieldBusquedaMarca = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        cmbBoxMarcasElimina = new javax.swing.JComboBox<>();
        btnEliminarMarcas = new javax.swing.JButton();
        btnRegresarElimina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        textFieldBusquedaMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldBusquedaMarcaActionPerformed(evt);
            }
        });
        textFieldBusquedaMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaMarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaMarcaKeyTyped(evt);
            }
        });

        lbl1.setText("Busqueda de marca");

        lbl2.setText("Marca a eliminar");

        btnEliminarMarcas.setText("Eliminar");
        btnEliminarMarcas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarMarcasActionPerformed(evt);
            }
        });

        btnRegresarElimina.setText("Regresar");
        btnRegresarElimina.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarEliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2)
                            .addComponent(lbl1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbBoxMarcasElimina, 0, 171, Short.MAX_VALUE)
                            .addComponent(textFieldBusquedaMarca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnEliminarMarcas)
                        .addGap(61, 61, 61)
                        .addComponent(btnRegresarElimina)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBusquedaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(cmbBoxMarcasElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMarcas)
                    .addComponent(btnRegresarElimina))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBusquedaMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldBusquedaMarcaActionPerformed
    {//GEN-HEADEREND:event_textFieldBusquedaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBusquedaMarcaActionPerformed

    private void btnRegresarEliminaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarEliminaActionPerformed
    {//GEN-HEADEREND:event_btnRegresarEliminaActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnRegresarEliminaActionPerformed

    private void textFieldBusquedaMarcaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaMarcaKeyTyped
    {//GEN-HEADEREND:event_textFieldBusquedaMarcaKeyTyped

    }//GEN-LAST:event_textFieldBusquedaMarcaKeyTyped

    private void btnEliminarMarcasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarMarcasActionPerformed
    {//GEN-HEADEREND:event_btnEliminarMarcasActionPerformed
        if (cmbBoxMarcasElimina.getSelectedIndex()!=-1)
        {
            String nomAEliminar= (String)cmbBoxMarcasElimina.getSelectedItem();
            
            String [] c=
            {
                nomAEliminar
            };
            
            
            Nodo [] nr=datos.getMultilista().elimina(c, 0, datos.getMultilista().getR());
            datos.getMultilista().setR(nr[1]);
            
            MenuPrincipal.muestraMensaje("Se elimino: "+nr[0].getEt());
        }else
        {
            MenuPrincipal.muestraMensaje("Escoje una marca con el combo box");
            
        }
    }//GEN-LAST:event_btnEliminarMarcasActionPerformed

    private void textFieldBusquedaMarcaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaMarcaKeyReleased
    {//GEN-HEADEREND:event_textFieldBusquedaMarcaKeyReleased
        cmbBoxMarcasElimina.removeAllItems();
        if (textFieldBusquedaMarca.getText().length() > 19)
        {
            evt.consume();
        }
        
        String subNombre= textFieldBusquedaMarca.getText();
        
        if (datos==null)
        {
            return;
        }
        
        Nodo auxBusqueda= datos.getMultilista().getR();
        ArrayList <String> cadenas= new ArrayList <String>();
        
        while (auxBusqueda!=null)
        {
            if (auxBusqueda.getEt().startsWith(subNombre.trim()))
            {
                cadenas.add(auxBusqueda.getEt());
            }
            auxBusqueda=auxBusqueda.getSig();
        }
        
        
        if (cadenas.size()!=0)
        {
            for (int i = 0; i < cadenas.size(); i++)
            {
                cmbBoxMarcasElimina.addItem(cadenas.get(i));
            }
        }
    }//GEN-LAST:event_textFieldBusquedaMarcaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cmbBoxMarcasElimina.removeAllItems();
        
        String subNombre= textFieldBusquedaMarca.getText();
        
        if (datos==null)
        {
            return;
        }
        
        Nodo auxBusqueda= datos.getMultilista().getR();
        ArrayList <String> cadenas= new ArrayList <String>();
        
        while (auxBusqueda!=null)
        {
            if (auxBusqueda.getEt().startsWith(subNombre.trim()))
            {
                cadenas.add(auxBusqueda.getEt());
            }
            auxBusqueda=auxBusqueda.getSig();
        }
        
        
        if (cadenas.size()!=0)
        {
            for (int i = 0; i < cadenas.size(); i++)
            {
                cmbBoxMarcasElimina.addItem(cadenas.get(i));
            }
        }
        cmbBoxMarcasElimina.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnEliminaMarcas(null, false,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMarcas;
    private javax.swing.JButton btnRegresarElimina;
    private javax.swing.JComboBox<String> cmbBoxMarcasElimina;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextField textFieldBusquedaMarca;
    // End of variables declaration//GEN-END:variables
}
