/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import clases.Servicios;

/**
 *
 * @author vllnm
 */
public class VtnModificarServicios extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnModificarServicios
     */
    public VtnModificarServicios(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel24 = new javax.swing.JLabel();
        cmbBoxSucursal = new javax.swing.JComboBox<>();
        cmbBoxCiudad = new javax.swing.JComboBox<>();
        cmbBoxMarca = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbBoxServicios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        textFieldNomServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldPrecioServicio = new javax.swing.JTextField();
        textFieldCupoServicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGuardarCambiosModificarServicios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel24.setText("Ciudad");

        cmbBoxSucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxSucursalActionPerformed(evt);
            }
        });

        cmbBoxCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxCiudadActionPerformed(evt);
            }
        });

        cmbBoxMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxMarcaActionPerformed(evt);
            }
        });

        jLabel21.setText("Sucursal");

        jLabel15.setText("Servicios");

        jLabel20.setText("Marca");

        cmbBoxServicios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxServiciosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevo nom servicio");

        jLabel2.setText("Nuevo precio servicio");

        jLabel3.setText("Nuevo cupo servicio");

        btnGuardarCambiosModificarServicios.setText("Guardar cambios");
        btnGuardarCambiosModificarServicios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarCambiosModificarServiciosActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldCupoServicio)
                                    .addComponent(cmbBoxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBoxSucursal, 0, 245, Short.MAX_VALUE)
                                    .addComponent(cmbBoxServicios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldNomServicio)
                                    .addComponent(textFieldPrecioServicio)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnGuardarCambiosModificarServicios)
                        .addGap(59, 59, 59)
                        .addComponent(btnRegresar)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel20)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmbBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmbBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNomServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCupoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambiosModificarServicios)
                    .addComponent(btnRegresar))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel20)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxSucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxSucursalActionPerformed
    {//GEN-HEADEREND:event_cmbBoxSucursalActionPerformed

        cmbBoxServicios.removeAllItems();

        String nomMarca = cmbBoxMarca.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudad.getSelectedItem().toString();
        String nomSuc = cmbBoxSucursal.getSelectedItem().toString();

        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);
        if (marca != null)
        {
            Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);
            if (ciudad != null)
            {
                Nodo sucursal = datos.getMultilista().busca(ciudad.getAbj(), nomSuc);

                if (sucursal != null)
                {
                    Nodo auxServicio = sucursal.getAbj();
                    while (auxServicio != null)
                    {
                        if (auxServicio.getObj() instanceof Servicios)
                        {
                            Servicios serv = (Servicios) auxServicio.getObj();
                            cmbBoxServicios.addItem(serv.getNom());
                        }
                        auxServicio = auxServicio.getSig();
                    }
                }
            }
        }

        // Reseteamos el combo para que no quede nada seleccionado
        cmbBoxServicios.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxSucursalActionPerformed

    private void cmbBoxCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxCiudadActionPerformed
    {//GEN-HEADEREND:event_cmbBoxCiudadActionPerformed
        cmbBoxSucursal.removeAllItems();

        if (cmbBoxMarca.getSelectedItem() == null || cmbBoxCiudad.getSelectedItem() == null)
        {
            return;
        }

        String nomMarca = cmbBoxMarca.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudad.getSelectedItem().toString();

        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);

        if (marca != null)
        {
            Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);

            if (ciudad != null)
            {
                Nodo auxSucursal = ciudad.getAbj();
                while (auxSucursal != null)
                {
                    cmbBoxSucursal.addItem(auxSucursal.getEt());
                    auxSucursal = auxSucursal.getSig();
                }
            }
        }

        cmbBoxSucursal.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxCiudadActionPerformed

    private void cmbBoxMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxMarcaActionPerformed
    {//GEN-HEADEREND:event_cmbBoxMarcaActionPerformed
        cmbBoxCiudad.removeAllItems();

        if (cmbBoxMarca.getSelectedIndex() == -1 || cmbBoxMarca.getSelectedItem() == null)
        {
            return;
        }

        String nombreMarca = cmbBoxMarca.getSelectedItem().toString();

        Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), nombreMarca);

        if (nodoMarca != null)
        {
            Nodo auxCiudad = nodoMarca.getAbj();
            while (auxCiudad != null)
            {
                cmbBoxCiudad.addItem(auxCiudad.getEt());
                auxCiudad = auxCiudad.getSig();
            }
        }

        cmbBoxCiudad.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxMarcaActionPerformed

    private void cmbBoxServiciosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxServiciosActionPerformed
    {//GEN-HEADEREND:event_cmbBoxServiciosActionPerformed
        if (cmbBoxServicios.getSelectedItem() == null)
        {
            textFieldNomServicio.setText("");
            textFieldPrecioServicio.setText("");
            textFieldCupoServicio.setText("");
            return;
        }

        String nombreServicio = cmbBoxServicios.getSelectedItem().toString();

        String nomMarca = cmbBoxMarca.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudad.getSelectedItem().toString();
        String nomSuc = cmbBoxSucursal.getSelectedItem().toString();

        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);
        Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);
        Nodo sucursal = datos.getMultilista().busca(ciudad.getAbj(), nomSuc);

        if (sucursal != null)
        {
            Nodo servicioNodo = datos.getMultilista().busca(sucursal.getAbj(), nombreServicio);

            if (servicioNodo != null && servicioNodo.getObj() instanceof Servicios)
            {
                Servicios serv = (Servicios) servicioNodo.getObj();

                textFieldNomServicio.setText(serv.getNom());
                textFieldPrecioServicio.setText(String.valueOf(serv.getPrecio()));
                textFieldCupoServicio.setText(serv.getCapacidad());
            }
        }
    }//GEN-LAST:event_cmbBoxServiciosActionPerformed

    private void btnGuardarCambiosModificarServiciosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarCambiosModificarServiciosActionPerformed
    {//GEN-HEADEREND:event_btnGuardarCambiosModificarServiciosActionPerformed

        if (cmbBoxMarca.getSelectedItem() == null || cmbBoxCiudad.getSelectedItem() == null
                || cmbBoxSucursal.getSelectedItem() == null || cmbBoxServicios.getSelectedItem() == null)
        {
            MenuPrincipal.muestraMensaje("Selecciona todos los niveles y un servicio a modificar");
            return;
        }

        String nuevoNombre = textFieldNomServicio.getText().trim();
        String precioStr = textFieldPrecioServicio.getText().trim();
        String cupoStr = textFieldCupoServicio.getText().trim();

        if (nuevoNombre.isEmpty())
        {
            MenuPrincipal.muestraMensaje("El nombre del servicio no puede estar vacío");
            return;
        }

        if (!precioStr.matches("\\d+(\\.\\d+)?"))
        {
            MenuPrincipal.muestraMensaje("El precio debe ser un número entero o decimal (ej: 100 o 100.50)");
            return;
        }

        if (!cupoStr.matches("\\d+"))
        {
            MenuPrincipal.muestraMensaje("La capacidad (cupo) debe ser un número entero");
            return;
        }

        String nomMarca = cmbBoxMarca.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudad.getSelectedItem().toString();
        String nomSuc = cmbBoxSucursal.getSelectedItem().toString();
        String servicioOriginal = cmbBoxServicios.getSelectedItem().toString();

        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);
        Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);
        Nodo sucursal = datos.getMultilista().busca(ciudad.getAbj(), nomSuc);
        Nodo servicioNodo = datos.getMultilista().busca(sucursal.getAbj(), servicioOriginal);

        if (servicioNodo != null)
        {

            Servicios serv = (Servicios) servicioNodo.getObj();
            serv.setNom(nuevoNombre);
            serv.setPrecio((int) Double.parseDouble(precioStr));
            serv.setCapacidad(cupoStr);
            servicioNodo.setEt(nuevoNombre);

            MenuPrincipal.muestraMensaje("Servicio actualizado correctamente");
        } else
        {
            MenuPrincipal.muestraMensaje("Error: No se pudo localizar el servicio para modificar");
        }
    }//GEN-LAST:event_btnGuardarCambiosModificarServiciosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarActionPerformed
    {//GEN-HEADEREND:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnModificarServicios dialog = new VtnModificarServicios(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void llenarComboMarcas()
    {
        cmbBoxMarca.removeAllItems();
        Nodo aux = datos.getMultilista().getR();
        while (aux != null)
        {
            cmbBoxMarca.addItem(aux.getEt());
            aux = aux.getSig();
        }
        cmbBoxMarca.setSelectedIndex(-1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambiosModificarServicios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbBoxCiudad;
    private javax.swing.JComboBox<String> cmbBoxMarca;
    private javax.swing.JComboBox<String> cmbBoxServicios;
    private javax.swing.JComboBox<String> cmbBoxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textFieldCupoServicio;
    private javax.swing.JTextField textFieldNomServicio;
    private javax.swing.JTextField textFieldPrecioServicio;
    // End of variables declaration//GEN-END:variables
}
