/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import clases.Sucursal;
import javax.swing.JOptionPane;

/**
 *
 * @author vllnm
 */
public class VtnModificaSucursal extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnModificaSucursal
     */
    public VtnModificaSucursal(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cmbBoxMarca = new javax.swing.JComboBox<>();
        cmbBoxCiudad = new javax.swing.JComboBox<>();
        cmbBoxSucursal = new javax.swing.JComboBox<>();
        textFieldNuevoNombre = new javax.swing.JTextField();
        textFieldNuevaDireccion = new javax.swing.JTextField();
        textFieldNuevoRes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        cmbBoxMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxMarcaActionPerformed(evt);
            }
        });

        cmbBoxCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxCiudadActionPerformed(evt);
            }
        });

        cmbBoxSucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxSucursalActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevo nombre de sucursal");

        jLabel2.setText("Nueva direccion de la sucursal");

        jLabel3.setText("Nuevo responsable");

        jLabel4.setText("Seleccionar marca");

        jLabel5.setText("Seleccionar ciudad");

        jLabel6.setText("Seleccionar sucursal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbBoxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldNuevoRes)
                                .addComponent(cmbBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldNuevoNombre)
                                .addComponent(textFieldNuevaDireccion))
                            .addComponent(cmbBoxCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(textFieldNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNuevoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxMarcaActionPerformed
    {//GEN-HEADEREND:event_cmbBoxMarcaActionPerformed

        cmbBoxCiudad.removeAllItems();
        if (cmbBoxMarca.getSelectedIndex() != -1)
        {
            Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), cmbBoxMarca.getSelectedItem().toString());
            Nodo aux = marca.getAbj();
            while (aux != null)
            {
                cmbBoxCiudad.addItem(aux.getEt());
                aux = aux.getSig();
            }
        }
    }//GEN-LAST:event_cmbBoxMarcaActionPerformed

    private void cmbBoxCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxCiudadActionPerformed
    {//GEN-HEADEREND:event_cmbBoxCiudadActionPerformed

        cmbBoxSucursal.removeAllItems();
        if (cmbBoxCiudad.getSelectedIndex() != -1)
        {
            Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), cmbBoxMarca.getSelectedItem().toString());
            Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), cmbBoxCiudad.getSelectedItem().toString());
            Nodo aux = ciudad.getAbj();
            while (aux != null)
            {
                cmbBoxSucursal.addItem(aux.getEt());
                aux = aux.getSig();
            }
        }

    }//GEN-LAST:event_cmbBoxCiudadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cargarMarcas();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        if (textFieldNuevoNombre.getText().isBlank()
                || textFieldNuevaDireccion.getText().isBlank()
                || textFieldNuevoRes.getText().isBlank())
        {
            MenuPrincipal.muestraMensaje("Escribe un nombre, responsable y dirección válidos");
            return;
        }

        String nomMarca = cmbBoxMarca.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudad.getSelectedItem().toString();
        String nomSuc = cmbBoxSucursal.getSelectedItem().toString();


        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);
        Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);
        Nodo sucursalNodo = datos.getMultilista().busca(ciudad.getAbj(), nomSuc);

        if (sucursalNodo != null && sucursalNodo.getObj() instanceof Sucursal)
        {
            Sucursal suc = (Sucursal) sucursalNodo.getObj();

            // Actualizar propiedades del objeto
            suc.setNom(textFieldNuevoNombre.getText().trim());
            suc.setDir(textFieldNuevaDireccion.getText().trim());
            suc.setResponsable(textFieldNuevoRes.getText().trim());

            sucursalNodo.setEt(suc.getNom());

            MenuPrincipal.muestraMensaje("Sucursal modificada correctamente");

        } else
        {
            MenuPrincipal.muestraMensaje("Error al encontrar la sucursal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbBoxSucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxSucursalActionPerformed
    {//GEN-HEADEREND:event_cmbBoxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnModificaSucursal dialog = new VtnModificaSucursal(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargarMarcas()
    {
        cmbBoxMarca.removeAllItems();
        Nodo aux = datos.getMultilista().getR();
        while (aux != null)
        {
            cmbBoxMarca.addItem(aux.getEt());
            aux = aux.getSig();
        }
        cmbBoxMarca.setSelectedIndex(-1);
    }

// Evento: Al seleccionar ciudad, llena sucursales

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBoxCiudad;
    private javax.swing.JComboBox<String> cmbBoxMarca;
    private javax.swing.JComboBox<String> cmbBoxSucursal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textFieldNuevaDireccion;
    private javax.swing.JTextField textFieldNuevoNombre;
    private javax.swing.JTextField textFieldNuevoRes;
    // End of variables declaration//GEN-END:variables
}
