/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import java.util.ArrayList;

/**
 *
 * @author vllnm
 */
public class VtnModificaNombreMarca extends javax.swing.JDialog
{
    Datos datos;
    /**
     * Creates new form VtnModificaNombreMarca
     */
    public VtnModificaNombreMarca(java.awt.Frame parent, boolean modal,Datos datosMenuPrincipal)
    {
        super(parent,modal);
        this.datos=datosMenuPrincipal;
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cmbBoxMarcaModificar = new javax.swing.JComboBox<>();
        textFieldNuevaMarca = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnGuardarModifica = new javax.swing.JButton();
        btnRegresarModifica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldBusquedaModifica = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textFieldNuevaMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                textFieldNuevaMarcaKeyPressed(evt);
            }
        });

        lbl1.setText("Marca a modificar");

        lbl2.setText("Nuevo nombre de Marca");

        btnGuardarModifica.setText("Guardar");
        btnGuardarModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarModificaActionPerformed(evt);
            }
        });

        btnRegresarModifica.setText("Regresar");
        btnRegresarModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarModificaActionPerformed(evt);
            }
        });

        jLabel1.setText("Busqueda Marca");

        textFieldBusquedaModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldBusquedaModificaActionPerformed(evt);
            }
        });
        textFieldBusquedaModifica.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaModificaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaModificaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnGuardarModifica)
                        .addGap(28, 28, 28)
                        .addComponent(btnRegresarModifica))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl1)
                                    .addComponent(jLabel1))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBoxMarcaModificar, 0, 201, Short.MAX_VALUE)
                                    .addComponent(textFieldNuevaMarca)
                                    .addComponent(textFieldBusquedaModifica))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldBusquedaModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxMarcaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(textFieldNuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarModifica)
                    .addComponent(btnRegresarModifica))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBusquedaModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldBusquedaModificaActionPerformed
    {//GEN-HEADEREND:event_textFieldBusquedaModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBusquedaModificaActionPerformed

    private void textFieldBusquedaModificaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaModificaKeyTyped
    {//GEN-HEADEREND:event_textFieldBusquedaModificaKeyTyped
 
    }//GEN-LAST:event_textFieldBusquedaModificaKeyTyped

    private void textFieldNuevaMarcaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldNuevaMarcaKeyPressed
    {//GEN-HEADEREND:event_textFieldNuevaMarcaKeyPressed
        if (textFieldBusquedaModifica.getText().length()>19)
        {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldNuevaMarcaKeyPressed

    private void btnGuardarModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarModificaActionPerformed
    {//GEN-HEADEREND:event_btnGuardarModificaActionPerformed
        
        String nom="";
        if (cmbBoxMarcaModificar.getSelectedIndex()!=-1)
        {
            nom= (String)cmbBoxMarcaModificar.getSelectedItem();
        }else
        {
            MenuPrincipal.muestraMensaje("Seleciona una Marca con la pestañita para Modificar su nombre");
            return;
        }
        

        String nuevoNom= textFieldNuevaMarca.getText();
        
        if (nuevoNom!=null&& !nuevoNom.isBlank())
        {
            Nodo nodoMod=datos.getMultilista().busca(datos.getMultilista().getR(), nom);
            nodoMod.setEt(nuevoNom);
            MenuPrincipal.muestraMensaje("Se ha modificado correctamente");
            textFieldBusquedaModifica.setText("");
            cmbBoxMarcaModificar.removeAllItems();
            textFieldNuevaMarca.setText("");
            System.out.println("LLego aca");
        }else
        {
            MenuPrincipal.muestraMensaje("Escribe el nuevo nombre para la Marca");
        }
    }//GEN-LAST:event_btnGuardarModificaActionPerformed

    private void btnRegresarModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarModificaActionPerformed
    {//GEN-HEADEREND:event_btnRegresarModificaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarModificaActionPerformed

    private void textFieldBusquedaModificaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaModificaKeyReleased
    {//GEN-HEADEREND:event_textFieldBusquedaModificaKeyReleased
        cmbBoxMarcaModificar.removeAllItems();
        if(textFieldBusquedaModifica.getText().length() > 19)
        {
            evt.consume();
        }
        
        String subNombre= textFieldBusquedaModifica.getText();
        
        if (datos==null)
        {
            return;
        }
        
        Nodo auxBusqueda= datos.getMultilista().getR();
        ArrayList <String> cadenas= new ArrayList <String>();
        
        while (auxBusqueda!=null)
        {
            if (auxBusqueda.getEt().startsWith(subNombre.trim()))
            {
                cadenas.add(auxBusqueda.getEt());
            }
            auxBusqueda=auxBusqueda.getSig();
        }
        
        
        if (cadenas.size()!=0)
        {
            for (int i = 0; i < cadenas.size(); i++)
            {
                cmbBoxMarcaModificar.addItem(cadenas.get(i));
            }
        }
    }//GEN-LAST:event_textFieldBusquedaModificaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaNombreMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaNombreMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaNombreMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaNombreMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnModificaNombreMarca(null,false,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarModifica;
    private javax.swing.JButton btnRegresarModifica;
    private javax.swing.JComboBox<String> cmbBoxMarcaModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextField textFieldBusquedaModifica;
    private javax.swing.JTextField textFieldNuevaMarca;
    // End of variables declaration//GEN-END:variables
}
