/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Ciudad;
import clases.Datos;
import clases.Nodo;
import clases.Validaciones;
import java.util.ArrayList;

/**
 *
 * @author vllnm
 */
public class VtnModificarNombreCiudad extends javax.swing.JDialog
{

    Datos datos;
    /**
     * Creates new form VtnModificarNombreCIudad
     */
    public VtnModificarNombreCiudad(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos=datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGuardarCambios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        textFieldBusquedaMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbBoxSeleccionMarca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldBusquedaCiudad = new javax.swing.JTextField();
        cmbBoxSeleccionCiudad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textFieldNuevoNomCiudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarActionPerformed(evt);
            }
        });

        textFieldBusquedaMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldBusquedaMarcaActionPerformed(evt);
            }
        });
        textFieldBusquedaMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaMarcaKeyReleased(evt);
            }
        });

        jLabel1.setText("Busqueda de Marca");

        cmbBoxSeleccionMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxSeleccionMarcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccion de Marca");

        jLabel3.setText("Busqueda de ciudad");

        textFieldBusquedaCiudad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldBusquedaCiudadKeyReleased(evt);
            }
        });

        jLabel4.setText("Seleccion de ciudad");

        jLabel5.setText("Nuevo nombre de ciudad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxSeleccionMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldBusquedaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(textFieldBusquedaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarCambios)
                        .addGap(108, 108, 108)
                        .addComponent(btnRegresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNuevoNomCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxSeleccionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldBusquedaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxSeleccionMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textFieldBusquedaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbBoxSeleccionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNuevoNomCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios)
                    .addComponent(btnRegresar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarCambiosActionPerformed
    {//GEN-HEADEREND:event_btnGuardarCambiosActionPerformed
        if (cmbBoxSeleccionMarca.getSelectedIndex()==-1)
        {
            MenuPrincipal.muestraMensaje("Selecciona una marca");
        }else
        {
            if (cmbBoxSeleccionCiudad.getSelectedIndex()==-1)
            {
                MenuPrincipal.muestraMensaje("Selecciona una ciudad a modificar");
            }else
            {
                if (textFieldNuevoNomCiudad.getText().isBlank())
                {
                    MenuPrincipal.muestraMensaje("Escribe un nombre para la ciudad");
                }else
                {
                    String nomCiudadNuevo = textFieldNuevoNomCiudad.getText().trim();
                    String nomMarcaMod = (String) cmbBoxSeleccionMarca.getSelectedItem();
                    String nomCiudadViejo = (String) cmbBoxSeleccionCiudad.getSelectedItem(); 

                    if (!Validaciones.validaNombre(nomCiudadNuevo)) 
                    {
                        MenuPrincipal.muestraMensaje("Prueba con otro nombre válido (Solo letras)");
                    } 
                    else 
                    {
                        Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarcaMod);

                        if (nodoMarca != null) 
                        {
                            Nodo existeNuevaCiudad = datos.getMultilista().busca(nodoMarca.getAbj(), nomCiudadNuevo);

                            if (existeNuevaCiudad != null) 
                            {
                                MenuPrincipal.muestraMensaje("La ciudad '" + nomCiudadNuevo + "' ya está registrada en esta marca. Elige otro nombre.");
                            } 
                            else 
                            {
                                Nodo nodoCiudadAModificar = datos.getMultilista().busca(nodoMarca.getAbj(), nomCiudadViejo);

                                if (nodoCiudadAModificar != null) 
                                {
                                    nodoCiudadAModificar.setEt(nomCiudadNuevo);
                                    nodoCiudadAModificar.setObj(new Ciudad(nomCiudadNuevo));
                                    MenuPrincipal.muestraMensaje("Ciudad modificada con éxito.");
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void textFieldBusquedaMarcaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaMarcaKeyReleased
    {//GEN-HEADEREND:event_textFieldBusquedaMarcaKeyReleased
        cmbBoxSeleccionMarca.removeAllItems();
        
        String subNombre= textFieldBusquedaMarca.getText();
        
        Nodo auxBusqueda= datos.getMultilista().getR();
        ArrayList <String> cadenas= new ArrayList <String>();
        
        while (auxBusqueda!=null)
        {
            if (auxBusqueda.getEt().startsWith(subNombre.trim()))
            {
                cadenas.add(auxBusqueda.getEt());
            }else
            {
                if (subNombre.isBlank())
                {
                    cadenas.add(auxBusqueda.getEt());
                }
            }
            auxBusqueda=auxBusqueda.getSig();
        }

        if (cadenas.size()!=0)
        {
            for (int i = 0; i < cadenas.size(); i++)
            {
                cmbBoxSeleccionMarca.addItem(cadenas.get(i));
            }
        }
        cmbBoxSeleccionMarca.setSelectedIndex(-1);
    }//GEN-LAST:event_textFieldBusquedaMarcaKeyReleased

    private void textFieldBusquedaCiudadKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldBusquedaCiudadKeyReleased
    {//GEN-HEADEREND:event_textFieldBusquedaCiudadKeyReleased
        cmbBoxSeleccionCiudad.removeAllItems();
       
        String nombreCiudad = textFieldBusquedaCiudad.getText().trim();
        String nombreMarca= textFieldBusquedaMarca.getText();
        
        ArrayList<String> ciudades = new ArrayList<>();

        
        Nodo auxMarca = datos.getMultilista().busca(datos.getMultilista().getR(),nombreMarca );

        if (auxMarca!=null)
        {
            
            Nodo auxCiudad = auxMarca.getAbj();

            
            while (auxCiudad != null) 
            {
                if (!ciudades.contains(auxCiudad.getEt())) 
                {
                    ciudades.add(auxCiudad.getEt());
                 }
                auxCiudad = auxCiudad.getSig();
            }
        }



        if (ciudades.size() != 0) 
        {
            for (int i = 0; i < ciudades.size(); i++) 
            {
                String ciudad = ciudades.get(i);

                if (ciudad != null && !ciudad.trim().isEmpty()) 
                {

                    cmbBoxSeleccionCiudad.addItem(ciudad); 
                }
            }
        } 

        cmbBoxSeleccionCiudad.setSelectedIndex(-1);
    }//GEN-LAST:event_textFieldBusquedaCiudadKeyReleased

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarActionPerformed
    {//GEN-HEADEREND:event_btnRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void textFieldBusquedaMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldBusquedaMarcaActionPerformed
    {//GEN-HEADEREND:event_textFieldBusquedaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBusquedaMarcaActionPerformed

    private void cmbBoxSeleccionMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxSeleccionMarcaActionPerformed
    {//GEN-HEADEREND:event_cmbBoxSeleccionMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxSeleccionMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarNombreCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarNombreCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarNombreCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificarNombreCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnModificarNombreCiudad dialog = new VtnModificarNombreCiudad(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbBoxSeleccionCiudad;
    private javax.swing.JComboBox<String> cmbBoxSeleccionMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFieldBusquedaCiudad;
    private javax.swing.JTextField textFieldBusquedaMarca;
    private javax.swing.JTextField textFieldNuevoNomCiudad;
    // End of variables declaration//GEN-END:variables
}
