/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Ciudad;
import clases.Datos;
import clases.Nodo;

/**
 *
 * @author vllnm
 */
public class VtnNuevaCiudad extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnNuevaCiudad
     */
    public VtnNuevaCiudad(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGuardarNuevaCiudad = new javax.swing.JButton();
        btnRegresarNuevaCiudad = new javax.swing.JButton();
        cmbBoxMarcasNuevaCiudad = new javax.swing.JComboBox<>();
        textFieldNuevaCiudad = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        btnGuardarNuevaCiudad.setText("Guardar ciudad");
        btnGuardarNuevaCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarNuevaCiudadActionPerformed(evt);
            }
        });

        btnRegresarNuevaCiudad.setText("Regresar");
        btnRegresarNuevaCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarNuevaCiudadActionPerformed(evt);
            }
        });

        lbl1.setText("Marca");

        lbl2.setText("Ciudad donde se instalara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnGuardarNuevaCiudad)
                        .addGap(51, 51, 51)
                        .addComponent(btnRegresarNuevaCiudad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addComponent(lbl2))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxMarcasNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxMarcasNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevaCiudad)
                    .addComponent(btnRegresarNuevaCiudad))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cargaDatosMarcas();
    }//GEN-LAST:event_formWindowOpened

    private void btnGuardarNuevaCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarNuevaCiudadActionPerformed
    {//GEN-HEADEREND:event_btnGuardarNuevaCiudadActionPerformed

        if (cmbBoxMarcasNuevaCiudad.getSelectedIndex() == -1 || textFieldNuevaCiudad.getText().isBlank())
        {
            MenuPrincipal.muestraMensaje("Selecciona una marca e introduce un nombre válido");
            return;
        }

        String marca = (String) cmbBoxMarcasNuevaCiudad.getSelectedItem();
        String nNodo = textFieldNuevaCiudad.getText().trim();

        Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), marca);

        if (nodoMarca == null)
        {
            MenuPrincipal.muestraMensaje("Error: No se encontró la marca en la base de datos.");
            return;
        }

        Nodo auxBusqueda = nodoMarca.getAbj();

        while (auxBusqueda != null)
        {
            if (auxBusqueda.getEt().equalsIgnoreCase(nNodo))
            {
                MenuPrincipal.muestraMensaje("Esta marca ya cuenta con esta ciudad");
                return;
            }
            auxBusqueda = auxBusqueda.getSig();
        }

        String[] c =
        {
            marca, nNodo
        };

        datos.getMultilista().setR(
                datos.getMultilista().inserta(new Nodo(new Ciudad(nNodo), nNodo), c, 0, datos.getMultilista().getR())
        );

        MenuPrincipal.muestraMensaje("Ciudad agregada exitosamente.");
    }//GEN-LAST:event_btnGuardarNuevaCiudadActionPerformed

    private void btnRegresarNuevaCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarNuevaCiudadActionPerformed
    {//GEN-HEADEREND:event_btnRegresarNuevaCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarNuevaCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnNuevaCiudad dialog = new VtnNuevaCiudad(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void cargaDatosMarcas()
    {
        cmbBoxMarcasNuevaCiudad.removeAllItems();

        Nodo aux = datos.getMultilista().getR();

        while (aux != null)
        {
            cmbBoxMarcasNuevaCiudad.addItem(aux.getEt());
            aux = aux.getSig();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarNuevaCiudad;
    private javax.swing.JButton btnRegresarNuevaCiudad;
    private javax.swing.JComboBox<String> cmbBoxMarcasNuevaCiudad;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextField textFieldNuevaCiudad;
    // End of variables declaration//GEN-END:variables
}
