/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import clases.Sucursal;
import javax.swing.JOptionPane;

/**
 *
 * @author vllnm
 */

public class VtnNuevaSucursal extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnNuevaSucursal
     */
    public VtnNuevaSucursal(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbBoxMarcas = new javax.swing.JComboBox<>();
        cmbBoxCiudades = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textFieldNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarNuevaSucursal = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textFieldDir = new javax.swing.JTextField();
        textFieldRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Selecciona Marca");

        jLabel2.setText("Selecciona Ciudad");

        cmbBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbBoxMarcas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxMarcasActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre nueva Sucursal");

        textFieldNom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldNomActionPerformed(evt);
            }
        });

        jLabel4.setText("Direccion");

        btnGuardarNuevaSucursal.setText("Guardar");
        btnGuardarNuevaSucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarNuevaSucursalActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel5.setText("Responsable");

        textFieldRes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnGuardarNuevaSucursal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbBoxMarcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBoxCiudades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldNom)
                            .addComponent(textFieldDir)
                            .addComponent(textFieldRes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbBoxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevaSucursal)
                    .addComponent(btnRegresar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarNuevaSucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarNuevaSucursalActionPerformed
    {//GEN-HEADEREND:event_btnGuardarNuevaSucursalActionPerformed
        

    
        // 1. Validaciones básicas
        if (cmbBoxMarcas.getSelectedIndex() == -1 || cmbBoxCiudades.getSelectedIndex() == -1
                || textFieldNom.getText().isBlank() || textFieldDir.getText().isBlank() || textFieldRes.getText().isBlank())
        {
            MenuPrincipal.muestraMensaje( "Por favor completa todos los campos");
            return;
        }

        String nomMarca = (String) cmbBoxMarcas.getSelectedItem();
        String nomCiudad = (String) cmbBoxCiudades.getSelectedItem();
        String nomSuc = textFieldNom.getText().trim();
        String dir = textFieldDir.getText().trim();
        String res = textFieldRes.getText().trim();

        // 2. Crear objeto Sucursal
        Sucursal nuevaSuc = new Sucursal(nomSuc, dir, res);

        // 3. Insertar en Multilista
        // Construimos la ruta: Marca -> Ciudad -> Sucursal
        String[] ruta =
        {
            nomMarca, nomCiudad, nomSuc
        };
        Nodo nuevoNodo = new Nodo(nuevaSuc, nomSuc);

        datos.getMultilista().setR(
                datos.getMultilista().inserta(nuevoNodo, ruta, 0, datos.getMultilista().getR())
        );

        JOptionPane.showMessageDialog(this, "Sucursal creada con éxito");
        this.dispose(); // Cerrar ventana
    }//GEN-LAST:event_btnGuardarNuevaSucursalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        llenarComboMarcas();
        llenarComboMarcas();
    }//GEN-LAST:event_formWindowOpened

    private void cmbBoxMarcasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxMarcasActionPerformed
    {//GEN-HEADEREND:event_cmbBoxMarcasActionPerformed
       

    cmbBoxCiudades.removeAllItems();
    if (cmbBoxMarcas.getSelectedIndex() != -1)
    {
        String nomMarca = (String) cmbBoxMarcas.getSelectedItem();
        Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);

        if (nodoMarca != null)
        {
            Nodo aux = nodoMarca.getAbj();
            while (aux != null)
            {
                cmbBoxCiudades.addItem(aux.getEt());
                aux = aux.getSig();
            }
        }
    }
    cmbBoxCiudades.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxMarcasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarActionPerformed
    {//GEN-HEADEREND:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void textFieldNomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldNomActionPerformed
    {//GEN-HEADEREND:event_textFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomActionPerformed

    private void textFieldResActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldResActionPerformed
    {//GEN-HEADEREND:event_textFieldResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex)
    {
        java.util.logging.Logger.getLogger(VtnNuevaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
        java.util.logging.Logger.getLogger(VtnNuevaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
        java.util.logging.Logger.getLogger(VtnNuevaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(VtnNuevaSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
        public void run()
        {
            VtnNuevaSucursal dialog = new VtnNuevaSucursal(new javax.swing.JFrame(), true, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter()
            {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e)
                {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    private void llenarComboMarcas()
{
    cmbBoxMarcas.removeAllItems();
    Nodo aux = datos.getMultilista().getR();
    while (aux != null)
    {
        cmbBoxMarcas.addItem(aux.getEt());
        aux = aux.getSig();
    }
    cmbBoxMarcas.setSelectedIndex(-1);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarNuevaSucursal;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbBoxCiudades;
    private javax.swing.JComboBox<String> cmbBoxMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFieldDir;
    private javax.swing.JTextField textFieldNom;
    private javax.swing.JTextField textFieldRes;
    // End of variables declaration//GEN-END:variables
}
