/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Nodo;
import clases.Servicios;
import clases.Validaciones;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author vllnm
 */
public class VtnNuevoServicio extends javax.swing.JDialog
{

    Datos datos;

    /**
     * Creates new form VtnNuevoServicio
     */
    public VtnNuevoServicio(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos = datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textFieldServicioCap = new javax.swing.JTextField();
        textFieldNomServicio = new javax.swing.JTextField();
        textFieldPrecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbBoxMarcaServicio = new javax.swing.JComboBox<>();
        cmbBoxSucursalServicios = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbBoxCiudadServicio = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setText("Nombre");

        jLabel13.setText("Capacidad");

        textFieldServicioCap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldServicioCapActionPerformed(evt);
            }
        });

        textFieldPrecio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldPrecioActionPerformed(evt);
            }
        });
        textFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textFieldPrecioKeyTyped(evt);
            }
        });

        jLabel12.setText("Precio");

        cmbBoxMarcaServicio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxMarcaServicioActionPerformed(evt);
            }
        });

        cmbBoxSucursalServicios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxSucursalServiciosActionPerformed(evt);
            }
        });

        jLabel20.setText("Marca");

        jLabel24.setText("Ciudad");

        jLabel21.setText("Sucursal");

        cmbBoxCiudadServicio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbBoxCiudadServicioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar servicio");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldNomServicio)
                                    .addComponent(textFieldPrecio)
                                    .addComponent(textFieldServicioCap, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbBoxSucursalServicios, 0, 245, Short.MAX_VALUE)
                            .addComponent(cmbBoxCiudadServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnGuardar)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel20)
                    .addGap(35, 35, 35)
                    .addComponent(cmbBoxMarcaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmbBoxCiudadServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxSucursalServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textFieldNomServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(textFieldServicioCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(cmbBoxMarcaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldServicioCapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldServicioCapActionPerformed
    {//GEN-HEADEREND:event_textFieldServicioCapActionPerformed

    }//GEN-LAST:event_textFieldServicioCapActionPerformed

    private void textFieldPrecioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldPrecioActionPerformed
    {//GEN-HEADEREND:event_textFieldPrecioActionPerformed

    }//GEN-LAST:event_textFieldPrecioActionPerformed

    private void textFieldPrecioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textFieldPrecioKeyTyped
    {//GEN-HEADEREND:event_textFieldPrecioKeyTyped

    }//GEN-LAST:event_textFieldPrecioKeyTyped

    private void cmbBoxMarcaServicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxMarcaServicioActionPerformed
    {//GEN-HEADEREND:event_cmbBoxMarcaServicioActionPerformed
        cmbBoxCiudadServicio.removeAllItems();

        if (cmbBoxMarcaServicio.getSelectedIndex() == -1 || cmbBoxMarcaServicio.getSelectedItem() == null)
        {
            return;
        }

        String nombreMarca = cmbBoxMarcaServicio.getSelectedItem().toString();

        Nodo nodoMarca = datos.getMultilista().busca(datos.getMultilista().getR(), nombreMarca);

        if (nodoMarca != null)
        {
            Nodo auxCiudad = nodoMarca.getAbj();
            while (auxCiudad != null)
            {
                cmbBoxCiudadServicio.addItem(auxCiudad.getEt());
                auxCiudad = auxCiudad.getSig();
            }
        }

        cmbBoxCiudadServicio.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxMarcaServicioActionPerformed

    private void cmbBoxSucursalServiciosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxSucursalServiciosActionPerformed
    {//GEN-HEADEREND:event_cmbBoxSucursalServiciosActionPerformed

    }//GEN-LAST:event_cmbBoxSucursalServiciosActionPerformed

    private void cmbBoxCiudadServicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbBoxCiudadServicioActionPerformed
    {//GEN-HEADEREND:event_cmbBoxCiudadServicioActionPerformed
        cmbBoxSucursalServicios.removeAllItems();

        if (cmbBoxMarcaServicio.getSelectedItem() == null || cmbBoxCiudadServicio.getSelectedItem() == null)
        {
            return;
        }

        String nomMarca = cmbBoxMarcaServicio.getSelectedItem().toString();
        String nomCiudad = cmbBoxCiudadServicio.getSelectedItem().toString();

        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);

        if (marca != null)
        {
            Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);

            if (ciudad != null)
            {
                Nodo auxSucursal = ciudad.getAbj();
                while (auxSucursal != null)
                {
                    cmbBoxSucursalServicios.addItem(auxSucursal.getEt());
                    auxSucursal = auxSucursal.getSig();
                }
            }
        }

        cmbBoxSucursalServicios.setSelectedIndex(-1);
    }//GEN-LAST:event_cmbBoxCiudadServicioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed
        // 1. Obtención y validación de datos
        String nomMarca = cmbBoxMarcaServicio.getSelectedItem() != null ? cmbBoxMarcaServicio.getSelectedItem().toString() : "";
        String nomCiudad = cmbBoxCiudadServicio.getSelectedItem() != null ? cmbBoxCiudadServicio.getSelectedItem().toString() : "";
        String nomSuc = cmbBoxSucursalServicios.getSelectedItem() != null ? cmbBoxSucursalServicios.getSelectedItem().toString() : "";
        String nomSe = textFieldNomServicio.getText().trim();
        String precioStr = textFieldPrecio.getText().trim();
        String capStr = textFieldServicioCap.getText().trim();

        if (nomMarca.isEmpty() || nomCiudad.isEmpty() || nomSuc.isEmpty())
        {
            MenuPrincipal.muestraMensaje("Selecciona marca, ciudad y sucursal");
            return;
        }

        if (!Validaciones.validaNombre(nomSe) || !precioStr.matches("\\d+") || !capStr.matches("\\d+"))
        {
            MenuPrincipal.muestraMensaje("Verifica: Nombre (letras), Precio y Capacidad (números)");
            return;
        }

        // 2. Búsqueda de la ruta en la Multilista
        Nodo marca = datos.getMultilista().busca(datos.getMultilista().getR(), nomMarca);
        if (marca == null)
        {
            return;
        }

        Nodo ciudad = datos.getMultilista().busca(marca.getAbj(), nomCiudad);
        if (ciudad == null)
        {
            return;
        }


        Nodo sucursal = datos.getMultilista().busca(ciudad.getAbj(), nomSe);
        if (sucursal == null)
        {
            return;
        }

        // VALIDACIÓN DIRECTA AQUÍ
        boolean duplicado = false;
        Nodo aux = sucursal.getAbj();
        while (aux != null)
        {
            if (aux.getEt().equalsIgnoreCase(nomSe))
            {
                duplicado = true;
                break;
            }
            aux = aux.getSig();
        }

        if (duplicado)
        {
            MenuPrincipal.muestraMensaje("El servicio " + nomSe + " ya existe en esta sucursal");
        } else
        {
            Servicios nuevoServ = new Servicios(nomSe, Integer.parseInt(precioStr), capStr);
            Nodo servicioNodo = new Nodo(nuevoServ, nomSe);
            String[] nivel =
            {
                nomMarca, nomCiudad, nomSuc, nomSe
            };

            datos.getMultilista().setR(datos.getMultilista().inserta(servicioNodo, nivel, 0, datos.getMultilista().getR()));
            MenuPrincipal.muestraMensaje("Servicio agregado correctamente");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnNuevoServicio dialog = new VtnNuevoServicio(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void llenarComboMarcas()
    {
        cmbBoxMarcaServicio.removeAllItems();
        Nodo aux = datos.getMultilista().getR();
        while (aux != null)
        {
            cmbBoxMarcaServicio.addItem(aux.getEt());
            aux = aux.getSig();
        }
        cmbBoxMarcaServicio.setSelectedIndex(-1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbBoxCiudadServicio;
    private javax.swing.JComboBox<String> cmbBoxMarcaServicio;
    private javax.swing.JComboBox<String> cmbBoxSucursalServicios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JTextField textFieldNomServicio;
    private javax.swing.JTextField textFieldPrecio;
    private javax.swing.JTextField textFieldServicioCap;
    // End of variables declaration//GEN-END:variables
}
