/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import clases.Datos;
import clases.Marca;
import clases.Nodo;
import clases.Validaciones;
import static interfaces.MenuPrincipal.muestraMensaje;

/**
 *
 * @author vllnm
 */
public class VtnNuevaMarca extends javax.swing.JDialog
{
    Datos datos;
    /**
     * Creates new form VtnNuevaMarca
     */
    public VtnNuevaMarca(java.awt.Frame parent, boolean modal, Datos datosMP)
    {
        super(parent, modal);
        this.datos=datosMP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGuardarMarcaNuevaMarca = new javax.swing.JButton();
        btnRegresarNuevaMarca = new javax.swing.JButton();
        textFieldNuevaMarca = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        scrollPaneNuevaMarca = new javax.swing.JScrollPane();
        textAreaMarcasNuevaMarca = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 200));

        btnGuardarMarcaNuevaMarca.setText("Guardar Marca");
        btnGuardarMarcaNuevaMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarMarcaNuevaMarcaActionPerformed(evt);
            }
        });

        btnRegresarNuevaMarca.setText("Regresar");
        btnRegresarNuevaMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarNuevaMarcaActionPerformed(evt);
            }
        });

        textFieldNuevaMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldNuevaMarcaActionPerformed(evt);
            }
        });

        lbl1.setText("Nombre de la nueva marca");

        textAreaMarcasNuevaMarca.setColumns(20);
        textAreaMarcasNuevaMarca.setRows(5);
        scrollPaneNuevaMarca.setViewportView(textAreaMarcasNuevaMarca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnGuardarMarcaNuevaMarca)
                        .addGap(40, 40, 40)
                        .addComponent(btnRegresarNuevaMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneNuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMarcaNuevaMarca)
                    .addComponent(btnRegresarNuevaMarca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(scrollPaneNuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldNuevaMarcaActionPerformed
    {//GEN-HEADEREND:event_textFieldNuevaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNuevaMarcaActionPerformed

    private void btnGuardarMarcaNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarMarcaNuevaMarcaActionPerformed
    {//GEN-HEADEREND:event_btnGuardarMarcaNuevaMarcaActionPerformed

        String nom = textFieldNuevaMarca.getText().trim();

        if (Validaciones.validaMarca(nom)) 
        {
            Nodo existe = datos.getMultilista().busca(datos.getMultilista().getR(), nom);

            if (existe == null)
            {
                String[] nivel = { nom };
                Nodo nuevaMarca = new Nodo(new Marca(nom), nom);

                datos.getMultilista().setR(
                    datos.getMultilista().inserta(nuevaMarca, nivel, 0, datos.getMultilista().getR())
                );

                textFieldNuevaMarca.setText("");
                muestraMensaje("Marca " + nom + " agregada exitosamente");
            } 
            else 
            {
                muestraMensaje("No se pudo insertar la marca porque ya existe");
            }
        } 
        else 
        {
            muestraMensaje("Nombre inválido. Ingresa solo letras.");
        }
    }//GEN-LAST:event_btnGuardarMarcaNuevaMarcaActionPerformed

    private void btnRegresarNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarNuevaMarcaActionPerformed
    {//GEN-HEADEREND:event_btnRegresarNuevaMarcaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarNuevaMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnNuevaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnNuevaMarca dialog = new VtnNuevaMarca(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMarcaNuevaMarca;
    private javax.swing.JButton btnRegresarNuevaMarca;
    private javax.swing.JLabel lbl1;
    private javax.swing.JScrollPane scrollPaneNuevaMarca;
    private javax.swing.JTextArea textAreaMarcasNuevaMarca;
    private javax.swing.JTextField textFieldNuevaMarca;
    // End of variables declaration//GEN-END:variables
}
